name: quiz_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.4

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  build_runner: ^2.3.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_riverpod: ^2.3.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  hooks_riverpod: ^2.3.4
  package_info_plus: ^3.1.0
  riverpod: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/test_banks/
  fonts:
    - family: neue-machina
      fonts:
        - asset: fonts/NeueMachina-Regular.otf
        - asset: fonts/NeueMachina-Ultrabold.otf
          weight: 900
    - family: maison-neue-mono
      fonts:
        - asset: fonts/Maison-Neue-Mono.ttf

